// <auto-generated />
namespace GadgetWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product13123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product13123));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031148505_product 13123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
